global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'homelab'
rule_files:
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['mon_node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['mon_cadvisor:8080']
  
  - job_name: 'stockavailability_consumer'
    static_configs:
      - targets: ['172.20.0.1:8088']
    metrics_path: '/actuator/prometheus'
